name: Check and send message

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: go run .
        env:
          TELEGRAM_APITOKEN: ${{ secrets.TELEGRAM_APITOKEN }}
          CHATID: ${{ secrets.CHATID }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
